baseURL = "https://stalwart-sable-b7b959.netlify.app/"
languageCode = "en-us"
title = "College Store"
theme = ""
paginate = 12

[params]
  brand = "College Store"
  description = "A fake ecommerce demo for a college project"

